run_test dot_simple_test1.test
run_test dot_simple_test2.test
run_test dot_simple_test3.test
run_test dot_simple_test4.test
run_test dot_simple_test5.test

run_test dot_complex_test1.test
run_test dot_complex_test2.test
run_test dot_complex_test3.test
run_test dot_complex_test4.test

run_test dot_error_test1.test