run_test cd_simple_test1.test
run_test cd_simple_test2.test
run_test cd_simple_test3.test
run_test cd_simple_test4.test
run_test cd_simple_test5.test
run_test cd_simple_test6.test

run_test cd_complex_test1.test
run_test cd_complex_test2.test