run_test echo1.test
run_test echo2.test
run_test echo3.test
run_test echo4.test
run_test echo5.test
run_test echo6.test
run_test echo7.test
run_test echo8.test
run_test echo9.test
run_test echo10.test
run_test echo11.test
run_test echo12.test
run_test echo13.test
run_test echo14.test
run_test echo15.test
run_test echo16.test
run_test echoMouli1.test
run_test echoMouli2.test